spring:
  application:
    name: cuenta-service

  datasource:
    url: jdbc:mysql://localhost:3306/devsu?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

    server:
      port: 8082

#  datasource:
#    url: jdbc:h2:mem:cuentadb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:

#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

